In [2]:
import pandas as pd

# Sample data from your datasets
data1 = {
    'Snoring Rate': [93.8, 91.64, 60, 85.76, 48.12, 56.88, 47, 50, 45.28, 55.52, 73.44, 59.28],
    'Respiration Rate': [25.68, 25.104, 20, 23.536, 17.248, 19.376, 16.8, 18, 16.112, 19.104, 21.344, 19.856],
    'Body Temp': [91.84, 91.552, 96, 90.768, 97.872, 95.376, 97.2, 99, 96.168, 95.104, 93.344, 95.856],
    'Limb Movement': [16.6, 15.88, 10, 13.92, 6.496, 9.376, 5.6, 8, 4.224, 9.104, 11.344, 9.856],
    'Blood Oxygen': [89.84, 89.552, 95, 88.768, 96.248, 94.064, 95.8, 97, 95.112, 93.656, 91.344, 94.784],
    'REM Eye Movement': [99.6, 98.88, 85, 96.92, 72.48, 83.44, 68, 80, 61.12, 82.76, 91.72, 84.64],
    'Sleeping Hours': [1.84, 1.552, 7, 0.768, 8.248, 6.376, 7.8, 9, 7.112, 6.104, 4.016, 6.856],
    'Heart Rate': [74.2, 72.76, 60, 68.84, 53.12, 58.44, 52, 55, 50.28, 57.76, 63.36, 59.64],
    'Stress Level': [3, 3, 1, 3, 0, 1, 0, 0, 0, 1, 2, 1]
}

data2 = {
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male'],
    'Age': [27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29],
    'Occupation': ['Software Engineer', 'Doctor', 'Doctor', 'Sales Representative', 'Sales Representative', 'Software Engineer', 'Teacher', 'Doctor', 'Doctor', 'Doctor', 'Doctor', 'Doctor'],
    'Sleep Duration': [6.1, 6.2, 6.2, 5.9, 5.9, 5.9, 6.3, 7.8, 7.8, 7.8, 75, 7.8],
    'Quality of Sleep': [6, 6, 6, 4, 4, 4, 6, 7, 7, 7, 6, 7],
    'Physical Activity Level': [42, 60, 60, 30, 30, 30, 40, 75, 75, 75, 75, 75],
    'Stress Level': [6, 8, 8, 8, 8, 8, 7, 6, 6, 6, 6, 6],
    'BMI Category': ['Overweight', 'Normal', 'Normal', 'Obese', 'Obese', 'Obese', 'Obese', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal'],
    'Blood Pressure': ['126/83', '125/80', '125/80', '140/90', '140/90', '140/90', '140/90', '120/80', '120/80', '120/80', '120/80', '120/80'],
    'Heart Rate': [77, 75, 75, 85, 85, 85, 82, 70, 70, 70, 70, 70],
    'Daily Steps': [4200, 10000, 10000, 3000, 3000, 3000, 3500, 8000, 8000, 8000, 8000, 8000],
    'Sleep Disorder': ['None', 'None', 'None', 'Sleep Apnea', 'Sleep Apnea', 'Insomnia', 'Insomnia', 'None', 'None', 'None', 'None', 'None']
}

# Create dataframes
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [7]:

df2

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
7,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
8,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
9,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None
10,Male,29,Doctor,75.0,6,75,6,Normal,120/80,70,8000,None
11,Male,29,Doctor,7.8,7,75,6,Normal,120/80,70,8000,None

In [11]:
# Round the 'Stress Level' column in df1
df1['Stress Level'] = df1['Stress Level'].round().astype(int)

# Merge datasets based on common features 'Heart Rate' and 'Stress Level'
merged_df = pd.merge(df1, df2, on=['Heart Rate', 'Stress Level'], how='inner')

# Handle missing values if any
merged_df = merged_df.fillna(method='ffill')

# Encode categorical variables
merged_df = pd.get_dummies(merged_df, columns=['Gender', 'Occupation', 'BMI Category', 'Blood Pressure', 'Sleep Disorder'], drop_first=True)

# Display the updated dataframe
merged_df

C:\Users\musab\AppData\Local\Temp\ipykernel_21516\2660468878.py:5: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  merged_df = pd.merge(df1, df2, on=['Heart Rate', 'Stress Level'], how='inner')
C:\Users\musab\AppData\Local\Temp\ipykernel_21516\2660468878.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  merged_df = merged_df.fillna(method='ffill')

Empty DataFrame
Columns: [Snoring Rate, Respiration Rate, Body Temp, Limb Movement, Blood Oxygen, REM Eye Movement, Sleeping Hours, Heart Rate, Stress Level, Age, Sleep Duration, Quality of Sleep, Physical Activity Level, Daily Steps]
Index: []

In [1]:
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification

# Create a small synthetic dataset
X, y = make_classification(
    n_samples=100, 
    n_features=5, 
    n_classes=2, 
    weights=[0.9, 0.1],  # 90% in class 0, 10% in class 1
    random_state=42
)

# Convert the array to a DataFrame
df = pd.DataFrame(X, columns=[f'Feature_{i}' for i in range(1, 6)])
df['Stress Level'] = y

# Display the original dataset
print("Original Dataset:")
print(df['Stress Level'].value_counts())
print(df.head())

# Apply SMOTE for oversampling
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Create a new DataFrame with the resampled data
resampled_df = pd.DataFrame(X_resampled, columns=[f'Feature_{i}' for i in range(1, 6)])
resampled_df['Stress Level'] = y_resampled

# Display the resampled dataset
print("\nResampled Dataset:")
print(resampled_df['Stress Level'].value_counts())
print(resampled_df.head())

ModuleNotFoundError: No module named 'imblearn'

In [ ]:
data1 = {
    'Snoring Rate' 
    'Respiration Rate' 
    'Body Temp' 
    'Limb Movement' 
    'Blood Oxygen' 
    'REM Eye Movement'
    'Sleeping Hours' 
    'Heart Rate' 
    'Stress Level' 
}

data2 = {
    'Gender'
    'Age'-
    'Occupation' 
    'Sleep Duration' 
    'Quality of Sleep' 
    'Physical Activity Level'
    'Stress Level'
    'BMI Category' 
    'Blood Pressure' 
    'Heart Rate' 
    'Daily Steps' 
    'Sleep Disorder'
}